config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'palindromes#new'
  resources :palindromes, only: %i[index show destroy new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/palindrome.rb
# frozen_string_literal: true

# Palindrome model
class Palindrome < ApplicationRecord
  validates :input, presence: { message: 'Пустой ввод. Введите что-нибудь!' }, uniqueness: true,
                    format: { with: /\A(\d*)\z/, message: 'Введите только одно число!' }

  def self.search(search)
    if search
      where(input: search)
    else
      all
    end
  end

  def self.search_id(search)
    select(:id).find_by(input: search) if search
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/palindromes_controller.rb
# frozen_string_literal: true

require 'nokogiri'

class PalindromesController < ApplicationController
  before_action :set_palindrome, only: %i[show edit update destroy]
  XSLT_SERVER_TRANSFORM = "#{Rails.root}/public/server_transform.xslt".freeze

  def input; end

  # GET /palindromes or /palindromes.json
  def index
    @palindromes = Palindrome.all

    respond_to do |format|
      format.html do
        render 'index'
      end
      format.xml do
        xml_arr = @palindromes.inject([]) { |acc, el| acc.append el.output }
        doc_result = Nokogiri::XML('<db></db>')
        xml_arr.each_with_object(doc_result) do |el, acc|
          el = Nokogiri::XML(el).search('output')
          acc.at('db').add_child(el)
        end
        render xml: doc_result
      end
    end
  end

  # GET /palindromes/1 or /palindromes/1.json
  def show
    doc = Nokogiri::XML(@palindrome.output)
    xslt = Nokogiri::XSLT(File.read(XSLT_SERVER_TRANSFORM))
    @view = xslt.transform(doc)
  end

  # GET /palindromes/new
  def new
    @palindrome = Palindrome.new
  end

  # GET /palindromes/1/edit
  def edit; end

  # POST /palindromes or /palindromes.json
  def create
    found_id = Palindrome.search_id(palindrome_params[:input])
    if found_id.nil?
      @palindrome = Palindrome.new(palindrome_params)
      @palindrome.output = make_output(palindrome_params[:input]) if @palindrome.valid?
      found_id = @palindrome.id
      respond_to do |format|
        if @palindrome.save
          format.html { redirect_to @palindrome, notice: 'Палиндром успешно создан.' }
          format.json { render :show, status: :created, location: @palindrome }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @palindrome.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to action: 'show', id: found_id
    end
  end

  # DELETE /palindromes/1 or /palindromes/1.json
  def destroy
    @palindrome.destroy
    respond_to do |format|
      format.html { redirect_to palindromes_url, notice: 'Палиндром успешно удален.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_palindrome
    @palindrome = Palindrome.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def palindrome_params
    params.require(:palindrome).permit(:input)
  end

  def make_output(input)
    input  = Integer(input)
    return if input.nil?

    numbers = (0..input).select { |i| palindrome?(i * i) }
    result = numbers.size

    # palindromes_hash = numbers.map.with_index do |number, index|
    #   { "palindrome#{index + 1}": { number: number, square: number**2 } }
    # end

    palindromes_hash = numbers.map.with_index do |number, index|
      { index: index, number: number, square: number**2 }
    end

    output_hash = { result: result || 'Не найдено', palindromes: palindromes_hash }
    output_hash.to_xml(root: 'output')
  end

  def palindrome?(number)
    number.to_s == number.to_s.reverse
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/palindromes_helper.rb
# frozen_string_literal: true

module PalindromesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Palindromes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      .container{
        margin-top: 50px;
        margin-bottom: 50px;
      }
      button:active, button:focus {
        outline: none !important;
      }
      button::-moz-focus-inner {
        border: 0 !important;
      }
    </style>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/palindromes/_form.html.erb
<%= form_with(model: palindrome) do |form| %>
  <% if palindrome.errors.any? %>
    <div id="error_explanation">
      <h2>Пожалуйста, исправьте следующие ошибки ввода:</h2>

      <ul>
        <% palindrome.errors[:input].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group d-flex w-25">
    <%= form.text_field :input, type: 'text', placeholder: 'Введите n:', class: 'form-control', required: true %>
    <%= form.submit 'Найти', type: 'submit', class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/palindromes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Palindromes</h1>

<table>
  <thead align="center">
    <tr>
      <th>Введено</th>
      <th>Результат</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @palindromes.each do |palindrome| %>
      <tr>
        <td><%= palindrome.input %></td>
        <td><%= palindrome.output %></td>
        <td><%= link_to 'Посмотреть', palindrome, class: 'btn btn-link btn-sm' %></td>
        <td><%= link_to 'Удалить', palindrome, method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-link btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= link_to 'Ввести новое число', new_palindrome_path, class: 'btn btn-link btn-sm' %>
</div>

app/views/palindromes/new.html.erb
<h1>Palindromes</h1>
<p style="font-size: 16px">Введите n для поиска неотрицательных целых чисел, квадраты которых являются палиндромами. Например: 26^2 = 676.</p>

<%= render 'form', palindrome: @palindrome %><br/>

<%= link_to 'Вернуться на главную', palindromes_path, class: 'btn btn-link btn-sm' %>

app/views/palindromes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Palindromes</h1>

<p><strong>Вы ввели: </strong>
<%= @palindrome.input %></p>

<%== @view %>

<%= link_to 'На главную', palindromes_path, class: 'btn btn-link btn-sm' %>
<%= link_to 'Ввести новое число', new_palindrome_path, class: 'btn btn-link btn-sm' %>